<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cricket.proto

namespace App\Grpc\CricketPackage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cricketPackage.MatchScore</code>
 */
class MatchScore extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string score = 1;</code>
     */
    protected $score = '';
    /**
     * Generated from protobuf field <code>string timestamp = 2;</code>
     */
    protected $timestamp = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $score
     *     @type string $timestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cricket::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string score = 1;</code>
     * @return string
     */
    public function getScore()
    {
        return $this->score;
    }

    /**
     * Generated from protobuf field <code>string score = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setScore($var)
    {
        GPBUtil::checkString($var, True);
        $this->score = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string timestamp = 2;</code>
     * @return string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>string timestamp = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkString($var, True);
        $this->timestamp = $var;

        return $this;
    }

}

