<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cricket.proto

namespace App\Grpc\CricketPackage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cricketPackage.MatchRequest</code>
 */
class MatchRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 match_id = 1;</code>
     */
    protected $match_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $match_id
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\Cricket::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 match_id = 1;</code>
     * @return int
     */
    public function getMatchId()
    {
        return $this->match_id;
    }

    /**
     * Generated from protobuf field <code>int32 match_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMatchId($var)
    {
        GPBUtil::checkInt32($var);
        $this->match_id = $var;

        return $this;
    }

}