<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cricket.proto

namespace App\Grpc\CricketPackage;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cricketPackage.MatchResponse</code>
 */
class MatchResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 match_id = 1;</code>
     */
    protected $match_id = 0;
    /**
     * Generated from protobuf field <code>string team1 = 2;</code>
     */
    protected $team1 = '';
    /**
     * Generated from protobuf field <code>string team2 = 3;</code>
     */
    protected $team2 = '';
    /**
     * Generated from protobuf field <code>string result = 4;</code>
     */
    protected $result = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $match_id
     *     @type string $team1
     *     @type string $team2
     *     @type string $result
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\Cricket::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 match_id = 1;</code>
     * @return int
     */
    public function getMatchId()
    {
        return $this->match_id;
    }

    /**
     * Generated from protobuf field <code>int32 match_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMatchId($var)
    {
        GPBUtil::checkInt32($var);
        $this->match_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string team1 = 2;</code>
     * @return string
     */
    public function getTeam1()
    {
        return $this->team1;
    }

    /**
     * Generated from protobuf field <code>string team1 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTeam1($var)
    {
        GPBUtil::checkString($var, True);
        $this->team1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string team2 = 3;</code>
     * @return string
     */
    public function getTeam2()
    {
        return $this->team2;
    }

    /**
     * Generated from protobuf field <code>string team2 = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTeam2($var)
    {
        GPBUtil::checkString($var, True);
        $this->team2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string result = 4;</code>
     * @return string
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>string result = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkString($var, True);
        $this->result = $var;

        return $this;
    }

}